### ISSUE TITLE
Curseforge release

### ISSUE THREAD

**Issue by Madis0** [just-a-mango/SimplerOptions#3]
**Is your feature request related to a problem? Please describe.**
It would be nice to have it in Curseforge to make it easier to include this in modpacks.

**Describe the solution you'd like**
Release the mod in Curseforge

**Describe alternatives you've considered**
Request an exception in Curseforge

**Additional context**
N/A

**Comment by horacehoff** [comment]
That is indeed a very good idea, I will prepare the curseforge and notify you when it is approved.

**Comment by horacehoff** [comment]
https://www.curseforge.com/minecraft/mc-mods/simpler-options
You can now download it on Curseforge.
